### ISSUE TITLE
[defect] In the documentation - Start coding now! 

### ISSUE THREAD

**Issue by vegas3416** [watsonwork/watsonwork-developer-docs#14]
In the section of the documentation where it talks about "Start coding now!" 
There is a stub of code it tells you that you can copy and then to run a set of commands.

The commands are specific to Mac and should be addressed to show both Mac and Windows commands.

For me on Windows7 the commands that does what the Macs does is as follows:

Instead of export APP_ID for Windows you can use (again this is on Win7)  set APP_ID=<your app id> and same goes for the secret. To confirm that they took you can type: echo %APP_ID%

Then at the end instead of running $node filename.js  - you just type:   node filename.js

**Comment by vfrancis** [comment]
@miguelestrada you're updating this section, right? If not let me know and I'll take it on.
