### ISSUE TITLE
Incorrect meta link value causing double selection in doc navigator

### ISSUE THREAD

**Issue by ghost** [watsonwork/watsonwork-developer-docs#29]
<img width="300" alt="screen shot 2017-12-15 at 3 31 50 pm" src="https://user-images.githubusercontent.com/12887503/34059464-270c5a68-e1ad-11e7-9878-795600d3dfed.png">

In V1_HeresHowItWorks.md the link value in the meta info on the top of the document is not correct.
**current:**

copyright: 'Copyright IBM Corp. 2017'
link: 'watson-work-services-object-model'
is: 'published'

**should be:**

copyright: 'Copyright IBM Corp. 2017'
link: 'heres-how-it-works'
is: 'published'

**Comment by miguelestrada** [comment]
This was already addressed by https://github.com/watsonwork/watsonwork-developer-docs/pull/30.  Thanks for reporting :-)
