### ISSUE TITLE
Typo in "Get Started"

### ISSUE THREAD

**Issue by ghost** [watsonwork/watsonwork-developer-docs#76]
File V1_GetStarted.md, "fulfillment" ->  "fulfilment"

**Comment by jarusso** [comment]
Thanks for the feedback, references indicate either spelling is appropriate

![image](https://user-images.githubusercontent.com/8137296/40243791-234e4c6e-5a8f-11e8-99c8-8e8afe8919a1.png)

**Comment by ghost** [comment]
Ah - US vs British English strikes again!!

**Comment by jarusso** [comment]
indeed  - since I'm a practicing(practising) American I tend towards the Yankee way ;-)
