### ISSUE TITLE
Suggestions for "Listen to events in a space"

### ISSUE THREAD

**Issue by ghost** [watsonwork/watsonwork-developer-docs#78]
In V1_wwsg_Webhooks.md, title says "Outbound" but the first paragraph says "Outgoing". The term in "My Apps" is "outbound".

First reference to "Preparing your app to Run" would be useful if it were a link. Last reference to the same page is a link, but just says "Preparing your app" (missing "to run").
Item 2 in the image describing the events, "Watson Work Services returns and ID and secret": first "and" should be "an".
Item 6 contains "Service s" (extra space).

**Comment by jarusso** [comment]
thanks @johnhaslam we've fixed this
